{% set version = "2.9.0" %}

package:
  name: seqkit
  version: {{ version }}

source:
  url: https://github.com/shenwei356/seqkit/releases/download/v{{ version }}/seqkit_darwin_amd64.tar.gz # [osx]
  md5: c83d82188fbd83da765b5ae9939f5079 # [osx]

  url: https://github.com/shenwei356/seqkit/releases/download/v{{ version }}/seqkit_darwin_arm64.tar.gz # [arm64]
  md5: c6ddaa62d73280b645215143087dd1db # [arm64]

  url: https://github.com/shenwei356/seqkit/releases/download/v{{ version }}/seqkit_linux_amd64.tar.gz # [linux]
  md5: 5b5c5ba2796d45f42b2e61fde4d79821 # [linux]

  url: https://github.com/shenwei356/seqkit/releases/download/v{{ version }}/seqkit_linux_arm64.tar.gz # [aarch64]
  md5: 5cbca93de57c11d1f70d1e713a44be5a # [aarch64]

build:
  number: 0
  skip: False
  run_exports:
    - {{ pin_subpackage("seqkit", max_pin="x.x") }}
test:
  commands:
    - seqkit version --help

about:
  home: https://github.com/shenwei356/seqkit
  summary: a cross-platform and ultrafast toolkit for FASTA/Q file manipulation
  license: MIT

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  skip-lints:
    - should_be_noarch_generic
    - should_not_be_noarch_source
  identifiers:
    - biotools:seqkit
    - doi:10.1371/journal.pone.0163962
